"""adding Story class and associated relationships

Revision ID: 3ef402b5b854
Revises: 
Create Date: 2024-01-03 12:01:03.155957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef402b5b854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('teller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teller_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_person_association',
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['story.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_person_association')
    op.drop_table('story')
    # ### end Alembic commands ###
